/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlatformRouteRouteImport } from './routes/_authenticated/platform/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAppWorkoutsRouteImport } from './routes/_authenticated/app/workouts'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app/progress'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app/messages'
import { Route as AuthenticatedAppCheckinRouteImport } from './routes/_authenticated/app/checkin'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminExercisesRouteImport } from './routes/_authenticated/admin/exercises'
import { Route as AuthenticatedAdminCheckinRouteImport } from './routes/_authenticated/admin/checkin'
import { Route as AuthenticatedPlatformGymsRouteRouteImport } from './routes/_authenticated/platform/gyms.route'
import { Route as AuthenticatedPlatformGymsIndexRouteImport } from './routes/_authenticated/platform/gyms.index'
import { Route as AuthenticatedAppWorkoutDayIdRouteImport } from './routes/_authenticated/app/workout.$dayId'
import { Route as AuthenticatedAdminReportsEngagementRouteImport } from './routes/_authenticated/admin/reports.engagement'
import { Route as AuthenticatedAdminReportsAttendanceRouteImport } from './routes/_authenticated/admin/reports.attendance'
import { Route as AuthenticatedAdminPlansNewRouteImport } from './routes/_authenticated/admin/plans.new'
import { Route as AuthenticatedAdminPlansPlanIdRouteImport } from './routes/_authenticated/admin/plans.$planId'
import { Route as AuthenticatedAdminMembersMemberIdRouteImport } from './routes/_authenticated/admin/members.$memberId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformRouteRoute =
  AuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAppWorkoutsRoute =
  AuthenticatedAppWorkoutsRouteImport.update({
    id: '/workouts',
    path: '/workouts',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCheckinRoute = AuthenticatedAppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExercisesRoute =
  AuthenticatedAdminExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckinRoute =
  AuthenticatedAdminCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPlatformGymsRouteRoute =
  AuthenticatedPlatformGymsRouteRouteImport.update({
    id: '/gyms',
    path: '/gyms',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)
const AuthenticatedPlatformGymsIndexRoute =
  AuthenticatedPlatformGymsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformGymsRouteRoute,
  } as any)
const AuthenticatedAppWorkoutDayIdRoute =
  AuthenticatedAppWorkoutDayIdRouteImport.update({
    id: '/workout/$dayId',
    path: '/workout/$dayId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAdminReportsEngagementRoute =
  AuthenticatedAdminReportsEngagementRouteImport.update({
    id: '/reports/engagement',
    path: '/reports/engagement',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsAttendanceRoute =
  AuthenticatedAdminReportsAttendanceRouteImport.update({
    id: '/reports/attendance',
    path: '/reports/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlansNewRoute =
  AuthenticatedAdminPlansNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminPlansRoute,
  } as any)
const AuthenticatedAdminPlansPlanIdRoute =
  AuthenticatedAdminPlansPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedAdminPlansRoute,
  } as any)
const AuthenticatedAdminMembersMemberIdRoute =
  AuthenticatedAdminMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedAdminMembersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/platform/gyms': typeof AuthenticatedPlatformGymsRouteRouteWithChildren
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/admin/plans': typeof AuthenticatedAdminPlansRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/admin/plans/$planId': typeof AuthenticatedAdminPlansPlanIdRoute
  '/admin/plans/new': typeof AuthenticatedAdminPlansNewRoute
  '/admin/reports/attendance': typeof AuthenticatedAdminReportsAttendanceRoute
  '/admin/reports/engagement': typeof AuthenticatedAdminReportsEngagementRoute
  '/app/workout/$dayId': typeof AuthenticatedAppWorkoutDayIdRoute
  '/platform/gyms/': typeof AuthenticatedPlatformGymsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/admin/plans': typeof AuthenticatedAdminPlansRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/admin/plans/$planId': typeof AuthenticatedAdminPlansPlanIdRoute
  '/admin/plans/new': typeof AuthenticatedAdminPlansNewRoute
  '/admin/reports/attendance': typeof AuthenticatedAdminReportsAttendanceRoute
  '/admin/reports/engagement': typeof AuthenticatedAdminReportsEngagementRoute
  '/app/workout/$dayId': typeof AuthenticatedAppWorkoutDayIdRoute
  '/platform/gyms': typeof AuthenticatedPlatformGymsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/_authenticated/platform/gyms': typeof AuthenticatedPlatformGymsRouteRouteWithChildren
  '/_authenticated/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/_authenticated/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/app/checkin': typeof AuthenticatedAppCheckinRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/admin/members/$memberId': typeof AuthenticatedAdminMembersMemberIdRoute
  '/_authenticated/admin/plans/$planId': typeof AuthenticatedAdminPlansPlanIdRoute
  '/_authenticated/admin/plans/new': typeof AuthenticatedAdminPlansNewRoute
  '/_authenticated/admin/reports/attendance': typeof AuthenticatedAdminReportsAttendanceRoute
  '/_authenticated/admin/reports/engagement': typeof AuthenticatedAdminReportsEngagementRoute
  '/_authenticated/app/workout/$dayId': typeof AuthenticatedAppWorkoutDayIdRoute
  '/_authenticated/platform/gyms/': typeof AuthenticatedPlatformGymsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/platform'
    | '/platform/gyms'
    | '/admin/checkin'
    | '/admin/exercises'
    | '/admin/members'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/templates'
    | '/app/checkin'
    | '/app/messages'
    | '/app/profile'
    | '/app/progress'
    | '/app/workouts'
    | '/admin/'
    | '/app/'
    | '/platform/'
    | '/admin/members/$memberId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/admin/reports/attendance'
    | '/admin/reports/engagement'
    | '/app/workout/$dayId'
    | '/platform/gyms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/checkin'
    | '/admin/exercises'
    | '/admin/members'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/templates'
    | '/app/checkin'
    | '/app/messages'
    | '/app/profile'
    | '/app/progress'
    | '/app/workouts'
    | '/admin'
    | '/app'
    | '/platform'
    | '/admin/members/$memberId'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/admin/reports/attendance'
    | '/admin/reports/engagement'
    | '/app/workout/$dayId'
    | '/platform/gyms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/platform'
    | '/_authenticated/platform/gyms'
    | '/_authenticated/admin/checkin'
    | '/_authenticated/admin/exercises'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/templates'
    | '/_authenticated/app/checkin'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/workouts'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/platform/'
    | '/_authenticated/admin/members/$memberId'
    | '/_authenticated/admin/plans/$planId'
    | '/_authenticated/admin/plans/new'
    | '/_authenticated/admin/reports/attendance'
    | '/_authenticated/admin/reports/engagement'
    | '/_authenticated/app/workout/$dayId'
    | '/_authenticated/platform/gyms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/workouts': {
      id: '/_authenticated/app/workouts'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AuthenticatedAppWorkoutsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/checkin': {
      id: '/_authenticated/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AuthenticatedAppCheckinRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exercises': {
      id: '/_authenticated/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AuthenticatedAdminExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/checkin': {
      id: '/_authenticated/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AuthenticatedAdminCheckinRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/platform/gyms': {
      id: '/_authenticated/platform/gyms'
      path: '/gyms'
      fullPath: '/platform/gyms'
      preLoaderRoute: typeof AuthenticatedPlatformGymsRouteRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
    '/_authenticated/platform/gyms/': {
      id: '/_authenticated/platform/gyms/'
      path: '/'
      fullPath: '/platform/gyms/'
      preLoaderRoute: typeof AuthenticatedPlatformGymsIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformGymsRouteRoute
    }
    '/_authenticated/app/workout/$dayId': {
      id: '/_authenticated/app/workout/$dayId'
      path: '/workout/$dayId'
      fullPath: '/app/workout/$dayId'
      preLoaderRoute: typeof AuthenticatedAppWorkoutDayIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/reports/engagement': {
      id: '/_authenticated/admin/reports/engagement'
      path: '/reports/engagement'
      fullPath: '/admin/reports/engagement'
      preLoaderRoute: typeof AuthenticatedAdminReportsEngagementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports/attendance': {
      id: '/_authenticated/admin/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/admin/reports/attendance'
      preLoaderRoute: typeof AuthenticatedAdminReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/plans/new': {
      id: '/_authenticated/admin/plans/new'
      path: '/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof AuthenticatedAdminPlansNewRouteImport
      parentRoute: typeof AuthenticatedAdminPlansRoute
    }
    '/_authenticated/admin/plans/$planId': {
      id: '/_authenticated/admin/plans/$planId'
      path: '/$planId'
      fullPath: '/admin/plans/$planId'
      preLoaderRoute: typeof AuthenticatedAdminPlansPlanIdRouteImport
      parentRoute: typeof AuthenticatedAdminPlansRoute
    }
    '/_authenticated/admin/members/$memberId': {
      id: '/_authenticated/admin/members/$memberId'
      path: '/$memberId'
      fullPath: '/admin/members/$memberId'
      preLoaderRoute: typeof AuthenticatedAdminMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedAdminMembersRoute
    }
  }
}

interface AuthenticatedAdminMembersRouteChildren {
  AuthenticatedAdminMembersMemberIdRoute: typeof AuthenticatedAdminMembersMemberIdRoute
}

const AuthenticatedAdminMembersRouteChildren: AuthenticatedAdminMembersRouteChildren =
  {
    AuthenticatedAdminMembersMemberIdRoute:
      AuthenticatedAdminMembersMemberIdRoute,
  }

const AuthenticatedAdminMembersRouteWithChildren =
  AuthenticatedAdminMembersRoute._addFileChildren(
    AuthenticatedAdminMembersRouteChildren,
  )

interface AuthenticatedAdminPlansRouteChildren {
  AuthenticatedAdminPlansPlanIdRoute: typeof AuthenticatedAdminPlansPlanIdRoute
  AuthenticatedAdminPlansNewRoute: typeof AuthenticatedAdminPlansNewRoute
}

const AuthenticatedAdminPlansRouteChildren: AuthenticatedAdminPlansRouteChildren =
  {
    AuthenticatedAdminPlansPlanIdRoute: AuthenticatedAdminPlansPlanIdRoute,
    AuthenticatedAdminPlansNewRoute: AuthenticatedAdminPlansNewRoute,
  }

const AuthenticatedAdminPlansRouteWithChildren =
  AuthenticatedAdminPlansRoute._addFileChildren(
    AuthenticatedAdminPlansRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCheckinRoute: typeof AuthenticatedAdminCheckinRoute
  AuthenticatedAdminExercisesRoute: typeof AuthenticatedAdminExercisesRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRouteWithChildren
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminReportsAttendanceRoute: typeof AuthenticatedAdminReportsAttendanceRoute
  AuthenticatedAdminReportsEngagementRoute: typeof AuthenticatedAdminReportsEngagementRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCheckinRoute: AuthenticatedAdminCheckinRoute,
    AuthenticatedAdminExercisesRoute: AuthenticatedAdminExercisesRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRouteWithChildren,
    AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRouteWithChildren,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminReportsAttendanceRoute:
      AuthenticatedAdminReportsAttendanceRoute,
    AuthenticatedAdminReportsEngagementRoute:
      AuthenticatedAdminReportsEngagementRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCheckinRoute: typeof AuthenticatedAppCheckinRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppWorkoutsRoute: typeof AuthenticatedAppWorkoutsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppWorkoutDayIdRoute: typeof AuthenticatedAppWorkoutDayIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCheckinRoute: AuthenticatedAppCheckinRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppWorkoutsRoute: AuthenticatedAppWorkoutsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppWorkoutDayIdRoute: AuthenticatedAppWorkoutDayIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedPlatformGymsRouteRouteChildren {
  AuthenticatedPlatformGymsIndexRoute: typeof AuthenticatedPlatformGymsIndexRoute
}

const AuthenticatedPlatformGymsRouteRouteChildren: AuthenticatedPlatformGymsRouteRouteChildren =
  {
    AuthenticatedPlatformGymsIndexRoute: AuthenticatedPlatformGymsIndexRoute,
  }

const AuthenticatedPlatformGymsRouteRouteWithChildren =
  AuthenticatedPlatformGymsRouteRoute._addFileChildren(
    AuthenticatedPlatformGymsRouteRouteChildren,
  )

interface AuthenticatedPlatformRouteRouteChildren {
  AuthenticatedPlatformGymsRouteRoute: typeof AuthenticatedPlatformGymsRouteRouteWithChildren
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteRouteChildren: AuthenticatedPlatformRouteRouteChildren =
  {
    AuthenticatedPlatformGymsRouteRoute:
      AuthenticatedPlatformGymsRouteRouteWithChildren,
    AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  }

const AuthenticatedPlatformRouteRouteWithChildren =
  AuthenticatedPlatformRouteRoute._addFileChildren(
    AuthenticatedPlatformRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedPlatformRouteRoute: typeof AuthenticatedPlatformRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedPlatformRouteRoute: AuthenticatedPlatformRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
