
ALTER TABLE public.workout_plans
  ADD COLUMN IF NOT EXISTS is_template boolean NOT NULL DEFAULT false;

INSERT INTO public.exercises (gym_id, name, description, video_url, thumbnail_url, muscle_groups, equipment, difficulty, created_by)
VALUES
  (NULL, 'Barbell Bench Press', 'Classic compound chest press performed on a flat bench.', 'https://videos.fitforge.app/exercises/barbell-bench-press.mp4', 'https://cdn.fitforge.app/exercises/barbell-bench-press.jpg', ARRAY['chest','triceps','shoulders'], ARRAY['barbell','bench'], 'intermediate', NULL),
  (NULL, 'Incline Dumbbell Press', 'Upper-chest focused press on a 30–45° incline.', 'https://videos.fitforge.app/exercises/incline-dumbbell-press.mp4', 'https://cdn.fitforge.app/exercises/incline-dumbbell-press.jpg', ARRAY['chest','shoulders'], ARRAY['dumbbells','bench'], 'intermediate', NULL),
  (NULL, 'Push Up', 'Bodyweight horizontal press, scalable for all levels.', 'https://videos.fitforge.app/exercises/push-up.mp4', 'https://cdn.fitforge.app/exercises/push-up.jpg', ARRAY['chest','triceps','core'], ARRAY['bodyweight'], 'beginner', NULL),
  (NULL, 'Cable Chest Fly', 'Isolation movement that stretches and contracts the pecs.', 'https://videos.fitforge.app/exercises/cable-chest-fly.mp4', 'https://cdn.fitforge.app/exercises/cable-chest-fly.jpg', ARRAY['chest'], ARRAY['cable'], 'beginner', NULL),
  (NULL, 'Dumbbell Pullover', 'Stretch-loaded movement targeting chest and lats.', 'https://videos.fitforge.app/exercises/dumbbell-pullover.mp4', 'https://cdn.fitforge.app/exercises/dumbbell-pullover.jpg', ARRAY['chest','back'], ARRAY['dumbbells','bench'], 'intermediate', NULL),
  (NULL, 'Pull Up', 'Bodyweight vertical pull for back and biceps.', 'https://videos.fitforge.app/exercises/pull-up.mp4', 'https://cdn.fitforge.app/exercises/pull-up.jpg', ARRAY['back','biceps'], ARRAY['pull-up bar'], 'advanced', NULL),
  (NULL, 'Lat Pulldown', 'Machine vertical pull, great pull-up regression.', 'https://videos.fitforge.app/exercises/lat-pulldown.mp4', 'https://cdn.fitforge.app/exercises/lat-pulldown.jpg', ARRAY['back','biceps'], ARRAY['cable','machine'], 'beginner', NULL),
  (NULL, 'Barbell Row', 'Bent-over horizontal pull targeting mid back.', 'https://videos.fitforge.app/exercises/barbell-row.mp4', 'https://cdn.fitforge.app/exercises/barbell-row.jpg', ARRAY['back','biceps'], ARRAY['barbell'], 'intermediate', NULL),
  (NULL, 'Seated Cable Row', 'Horizontal pull with constant cable tension.', 'https://videos.fitforge.app/exercises/seated-cable-row.mp4', 'https://cdn.fitforge.app/exercises/seated-cable-row.jpg', ARRAY['back','biceps'], ARRAY['cable','machine'], 'beginner', NULL),
  (NULL, 'Conventional Deadlift', 'Full posterior chain compound from the floor.', 'https://videos.fitforge.app/exercises/conventional-deadlift.mp4', 'https://cdn.fitforge.app/exercises/conventional-deadlift.jpg', ARRAY['back','hamstrings','glutes'], ARRAY['barbell'], 'advanced', NULL),
  (NULL, 'Back Squat', 'King of lower-body lifts; barbell on upper back.', 'https://videos.fitforge.app/exercises/back-squat.mp4', 'https://cdn.fitforge.app/exercises/back-squat.jpg', ARRAY['quadriceps','glutes','core'], ARRAY['barbell','rack'], 'advanced', NULL),
  (NULL, 'Front Squat', 'Quad-dominant squat with bar in front rack.', 'https://videos.fitforge.app/exercises/front-squat.mp4', 'https://cdn.fitforge.app/exercises/front-squat.jpg', ARRAY['quadriceps','core'], ARRAY['barbell','rack'], 'advanced', NULL),
  (NULL, 'Romanian Deadlift', 'Hip hinge emphasizing hamstrings and glutes.', 'https://videos.fitforge.app/exercises/romanian-deadlift.mp4', 'https://cdn.fitforge.app/exercises/romanian-deadlift.jpg', ARRAY['hamstrings','glutes','back'], ARRAY['barbell'], 'intermediate', NULL),
  (NULL, 'Walking Lunge', 'Unilateral lower-body builder with each step.', 'https://videos.fitforge.app/exercises/walking-lunge.mp4', 'https://cdn.fitforge.app/exercises/walking-lunge.jpg', ARRAY['quadriceps','glutes','hamstrings'], ARRAY['dumbbells'], 'beginner', NULL),
  (NULL, 'Bulgarian Split Squat', 'Rear-foot elevated single-leg squat.', 'https://videos.fitforge.app/exercises/bulgarian-split-squat.mp4', 'https://cdn.fitforge.app/exercises/bulgarian-split-squat.jpg', ARRAY['quadriceps','glutes'], ARRAY['dumbbells','bench'], 'intermediate', NULL),
  (NULL, 'Leg Press', 'Machine compound for quads and glutes.', 'https://videos.fitforge.app/exercises/leg-press.mp4', 'https://cdn.fitforge.app/exercises/leg-press.jpg', ARRAY['quadriceps','glutes'], ARRAY['machine'], 'beginner', NULL),
  (NULL, 'Leg Curl', 'Isolated hamstring curl on a machine.', 'https://videos.fitforge.app/exercises/leg-curl.mp4', 'https://cdn.fitforge.app/exercises/leg-curl.jpg', ARRAY['hamstrings'], ARRAY['machine'], 'beginner', NULL),
  (NULL, 'Standing Calf Raise', 'Loaded ankle plantarflexion for calves.', 'https://videos.fitforge.app/exercises/standing-calf-raise.mp4', 'https://cdn.fitforge.app/exercises/standing-calf-raise.jpg', ARRAY['calves'], ARRAY['machine'], 'beginner', NULL),
  (NULL, 'Overhead Press', 'Standing barbell shoulder press.', 'https://videos.fitforge.app/exercises/overhead-press.mp4', 'https://cdn.fitforge.app/exercises/overhead-press.jpg', ARRAY['shoulders','triceps'], ARRAY['barbell'], 'intermediate', NULL),
  (NULL, 'Dumbbell Shoulder Press', 'Seated/standing DB press for shoulders.', 'https://videos.fitforge.app/exercises/dumbbell-shoulder-press.mp4', 'https://cdn.fitforge.app/exercises/dumbbell-shoulder-press.jpg', ARRAY['shoulders','triceps'], ARRAY['dumbbells'], 'beginner', NULL),
  (NULL, 'Lateral Raise', 'Isolation for the side (medial) deltoids.', 'https://videos.fitforge.app/exercises/lateral-raise.mp4', 'https://cdn.fitforge.app/exercises/lateral-raise.jpg', ARRAY['shoulders'], ARRAY['dumbbells'], 'beginner', NULL),
  (NULL, 'Face Pull', 'Rear-delt and upper-back cable pull.', 'https://videos.fitforge.app/exercises/face-pull.mp4', 'https://cdn.fitforge.app/exercises/face-pull.jpg', ARRAY['shoulders','back'], ARRAY['cable'], 'beginner', NULL),
  (NULL, 'Barbell Curl', 'Classic barbell biceps curl.', 'https://videos.fitforge.app/exercises/barbell-curl.mp4', 'https://cdn.fitforge.app/exercises/barbell-curl.jpg', ARRAY['biceps'], ARRAY['barbell'], 'beginner', NULL),
  (NULL, 'Hammer Curl', 'Neutral-grip DB curl for biceps + brachialis.', 'https://videos.fitforge.app/exercises/hammer-curl.mp4', 'https://cdn.fitforge.app/exercises/hammer-curl.jpg', ARRAY['biceps','forearms'], ARRAY['dumbbells'], 'beginner', NULL),
  (NULL, 'Triceps Pushdown', 'Cable triceps isolation movement.', 'https://videos.fitforge.app/exercises/triceps-pushdown.mp4', 'https://cdn.fitforge.app/exercises/triceps-pushdown.jpg', ARRAY['triceps'], ARRAY['cable'], 'beginner', NULL),
  (NULL, 'Overhead Triceps Extension', 'Stretched-position triceps extension.', 'https://videos.fitforge.app/exercises/overhead-triceps-extension.mp4', 'https://cdn.fitforge.app/exercises/overhead-triceps-extension.jpg', ARRAY['triceps'], ARRAY['dumbbells'], 'beginner', NULL),
  (NULL, 'Plank', 'Isometric anti-extension core hold.', 'https://videos.fitforge.app/exercises/plank.mp4', 'https://cdn.fitforge.app/exercises/plank.jpg', ARRAY['core'], ARRAY['bodyweight'], 'beginner', NULL),
  (NULL, 'Hanging Leg Raise', 'Lower-ab focused hanging movement.', 'https://videos.fitforge.app/exercises/hanging-leg-raise.mp4', 'https://cdn.fitforge.app/exercises/hanging-leg-raise.jpg', ARRAY['core'], ARRAY['pull-up bar'], 'intermediate', NULL),
  (NULL, 'Cable Woodchopper', 'Rotational core movement on cables.', 'https://videos.fitforge.app/exercises/cable-woodchopper.mp4', 'https://cdn.fitforge.app/exercises/cable-woodchopper.jpg', ARRAY['core'], ARRAY['cable'], 'intermediate', NULL),
  (NULL, 'Russian Twist', 'Seated rotational core exercise.', 'https://videos.fitforge.app/exercises/russian-twist.mp4', 'https://cdn.fitforge.app/exercises/russian-twist.jpg', ARRAY['core'], ARRAY['bodyweight','dumbbells'], 'beginner', NULL);
